### PR TITLE
Build packages for Python 3.6 also

### PR DESCRIPTION
**Pull request by certik**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by certik** [comment]
@conda-forge-admin, please rerender

**Comment by certik** [comment]
Ping @conda-forge/core. What does the above message mean that the linter "ran into some issues"?

**Comment by isuruf** [comment]
Usually, the webservice needs to be restarted for a new version of conda-smithy or conda-forge-pinning. I've restarted. Please try again in five minutes.

**Comment by certik** [comment]
Ok, thanks!

**Comment by certik** [comment]
@conda-forge-admin, please rerender

**Comment by certik** [comment]
Thanks @isuruf, it seems to work.

**Pull request merged**
