### PR TITLE
Update LFortran to latest 0.21.2

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
@conda-forge-admin, please rerender

**Comment by Shaikh-Ubaid** [comment]
When I added `libzstd` as a host dependency, the CI passed. I removed `libzstd` (to check if the CI still passes) and it fails for linux:

```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/home/conda/feedstock_root/build_artifacts/lfortran_1696858077252/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/lfortran_1696858077252/test_tmp
+ test -f /home/conda/feedstock_root/build_artifacts/lfortran_1696858077252/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/lfortran
+ lfortran --help
lfortran: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
Tests failed for lfortran-0.21.2-hfc55251_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for lfortran-0.21.2-hfc55251_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

I think `libzstd` as static library is not working @certik.

**Comment by certik** [comment]
The static library only works with https://github.com/lfortran/lfortran/pull/2583, which is not released yet I think. Without that PR, LFortran always links zstd dynamically.

**Review by certik — APPROVED** [review]
It looks like this PR will pass, and it is a minimal change to get things working, so let's merge it and then iterate on this further with subsequent PRs as needed.

**Comment by certik** [comment]
@Shaikh-Ubaid thanks for figuring this out! This unblocks us to get releases going again.

Given the zstd situation and the overall fragility of depending on LLVM and other issues, let's now finish https://github.com/lfortran/lfortran-conda-testing/ to use this latest release: https://github.com/lfortran/lfortran-conda-testing/pull/2. It usually takes several hours from now for the new packages to become available.

**Comment by Shaikh-Ubaid** [comment]
> @Shaikh-Ubaid thanks for figuring this out! This unblocks us to get releases going again.
> 
> Given the zstd situation and the overall fragility of depending on LLVM and other issues, let's now finish https://github.com/lfortran/lfortran-conda-testing/ to use this latest release: [lfortran/lfortran-conda-testing#2](https://github.com/lfortran/lfortran-conda-testing/pull/2). It usually takes several hours from now for the new packages to become available.

Thank you for the review and merging. Sure, got it.

**Pull request merged**
